=== Hafflationist/ScenarioCreator/ScenarioCreator.Generation/resources/germanet/GN_V160/GN_V160_XML/germanet_objects.dtd
<!-- DTD for GermaNet lexical objects -->
<!-- Version 2.0, December 2009 -->
<!-- Last update: April 2014 -->
<!-- Copyright: Department of General and Computational Linguistics, Tuebingen University -->

<!ELEMENT synsets     (synset+)>

<!ELEMENT synset      (lexUnit+, paraphrase?)>
<!ATTLIST synset      id           ID                 #REQUIRED
                      category     (adj|nomen|verben) #REQUIRED
                      class        (Allgemein|Bewegung|Gefuehl|Geist|Gesellschaft|Koerper|Menge|
                      natPhaenomen|Ort|Pertonym|Perzeption|privativ|Relation|Substanz|Verhalten|
                      Zeit|Artefakt|Attribut|Besitz|Form|Geschehen|Gruppe|Kognition|Kommunikation|
                      Mensch|Motiv|Nahrung|natGegenstand|Pflanze|Tier|Tops|Koerperfunktion|
                      Konkurrenz|Kontakt|Lokation|Schoepfung|Veraenderung|Verbrauch)              #REQUIRED>

<!ELEMENT lexUnit     (orthForm, orthVar?, oldOrthForm?, oldOrthVar?, frame*, example*, compound?)>
<!ATTLIST lexUnit     id           ID       #REQUIRED
                      sense        CDATA    #REQUIRED
                      source       CDATA    #REQUIRED
                      namedEntity  (yes|no) #REQUIRED
                      artificial   (yes|no) #REQUIRED
                      styleMarking (yes|no) #REQUIRED>

<!ELEMENT orthForm    (#PCDATA)>
<!ELEMENT orthVar     (#PCDATA)>
<!ELEMENT oldOrthForm (#PCDATA)>
<!ELEMENT oldOrthVar  (#PCDATA)>
<!ELEMENT paraphrase  (#PCDATA)>
<!ELEMENT example     (text, exframe?)>
<!ELEMENT text        (#PCDATA)>
<!ELEMENT frame       (#PCDATA)>
<!ELEMENT exframe     (#PCDATA)>

<!ELEMENT compound    (modifier, modifier?, head)>

<!ELEMENT modifier    (#PCDATA)>
<!ATTLIST modifier    property (Abk체rzung|Konfix|Fremdwort|Affixoid|Wortgruppe|Eigenname|opaquesMorphem|gebundenesMorphem|freiesMorphem|virtuelleBildung|Konversion) #IMPLIED
                      category (Adjektiv|Nomen|Verb|Adverb|Pr채position|Partikel|Pronomen|Pr채fix|Verbalpartikel) #IMPLIED>

<!ELEMENT head        (#PCDATA)>
<!ATTLIST head        property (Abk체rzung|Konfix|Fremdwort|Affixoid|opaquesMorphem|virtuelleBildung) #IMPLIED>

=== Hafflationist/ScenarioCreator/ScenarioCreator.Generation/resources/germanet/GN_V160/GN_V160_XML/adj.natPhaenomen.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE synsets SYSTEM "germanet_objects.dtd">
<synsets>
<synset id="s2184" category="adj" class="natPhaenomen">
<lexUnit id="l3371" sense="1" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>klimatisch</orthForm>
</lexUnit>
</synset>
<synset id="s2185" category="adj" class="natPhaenomen">
<lexUnit id="l3372" sense="1" source="core" namedEntity="no" artificial="yes" styleMarking="no">
<orthForm>landschaftsspezifisch</orthForm>
</lexUnit>
</synset>
<synset id="s2186" category="adj" class="natPhaenomen">
<lexUnit id="l3373" sense="1" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>landschaftlich</orthForm>
</lexUnit>
</synset>
<synset id="s2187" category="adj" class="natPhaenomen">
<lexUnit id="l3374" sense="1" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>gebirgig</orthForm>
</lexUnit>
<lexUnit id="l3375" sense="1" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>bergig</orthForm>
</lexUnit>
<lexUnit id="l106906" sense="1" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>bergreich</orthForm>
</lexUnit>
</synset>
<synset id="s2188" category="adj" class="natPhaenomen">
<lexUnit id="l3376" sense="1" source="core" namedEntity="no" artificial="no" styleMarking="yes">
<orthForm>bergisch</orthForm>
</lexUnit>
</synset>
<synset id="s2189" category="adj" class="natPhaenomen">
<lexUnit id="l3377" sense="1" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>hügelig</orthForm>
<orthVar>hüglig</orthVar>
</lexUnit>
</synset>
<synset id="s2190" category="adj" class="natPhaenomen">
<lexUnit id="l3379" sense="1" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>flach</orthForm>
</lexUnit>
<lexUnit id="l3380" sense="1" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>eben</orthForm>
</lexUnit>
<lexUnit id="l3381" sense="1" source="core" namedEntity="no" artificial="no" styleMarking="yes">
<orthForm>platt</orthForm>
</lexUnit>
</synset>
<synset id="s2191" category="adj" class="natPhaenomen">
<lexUnit id="l3382" sense="2" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>fruchtbar</orthForm>
</lexUnit>
<lexUnit id="l3383" sense="1" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>urbar</orthForm>
</lexUnit>
<lexUnit id="l107454" sense="2" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>fertil</orthForm>
</lexUnit>
</synset>
<synset id="s2192" category="adj" class="natPhaenomen">
<lexUnit id="l3385" sense="1" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>bewohnbar</orthForm>
</lexUnit>
</synset>
<synset id="s2193" category="adj" class="natPhaenomen">
<lexUnit id="l3386" sense="2" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>unfruchtbar</orthForm>
</lexUnit>
<lexUnit id="l3387" sense="2" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>öde</orthForm>
<orthVar>öd</orthVar>
</lexUnit>
</synset>
<synset id="s2194" category="adj" class="natPhaenomen">
<lexUnit id="l3388" sense="1" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>seenreich</orthForm>
</lexUnit>
</synset>
<synset id="s2195" category="adj" class="natPhaenomen">
<lexUnit id="l3389" sense="1" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>karg</orthForm>
</lexUnit>
<lexUnit id="l3390" sense="2" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>kahl</orthForm>
</lexUnit>
</synset>
<synset id="s2196" category="adj" class="natPhaenomen">
<lexUnit id="l3391" sense="1" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>unbewohnbar</orthForm>
</lexUnit>
</synset>
<synset id="s2197" category="adj" class="natPhaenomen">
<lexUnit id="l3392" sense="3" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>üppig</orthForm>
</lexUnit>
</synset>
<synset id="s2198" category="adj" class="natPhaenomen">
<lexUnit id="l3394" sense="2" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>trocken</orthForm>
</lexUnit>
<lexUnit id="l106651" sense="1" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>arid</orthForm>
</lexUnit>
</synset>
<synset id="s2199" category="adj" class="natPhaenomen">
<lexUnit id="l3395" sense="1" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>trocken-kalt</orthForm>
</lexUnit>
</synset>
<synset id="s2200" category="adj" class="natPhaenomen">
<lexUnit id="l3396" sense="1" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>feucht</orthForm>
</lexUnit>
<lexUnit id="l107897" sense="1" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>humid</orthForm>
</lexUnit>
</synset>
<synset id="s2201" category="adj" class="natPhaenomen">
<lexUnit id="l3397" sense="2" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>nass</orthForm>
<oldOrthForm>naß</oldOrthForm>
</lexUnit>
</synset>
<synset id="s2202" category="adj" class="natPhaenomen">
<lexUnit id="l3399" sense="1" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>feuchtwarm</orthForm>
</lexUnit>
</synset>
<synset id="s2203" category="adj" class="natPhaenomen">
<lexUnit id="l3400" sense="1" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>regnerisch</orthForm>
</lexUnit>
</synset>
<synset id="s2204" category="adj" class="natPhaenomen">
<lexUnit id="l3401" sense="1" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>gewittrig</orthForm>
</lexUnit>
<lexUnit id="l3402" sense="1" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>gewitterig</orthForm>
</lexUnit>
</synset>
<synset id="s2205" category="adj" class="natPhaenomen">
<lexUnit id="l3403" sense="1" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>wechselhaft-regnerisch</orthForm>
</lexUnit>
</synset>
<synset id="s2206" category="adj" class="natPhaenomen">
<lexUnit id="l3404" sense="1" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>schwül</orthForm>
</lexUnit>
<lexUnit id="l3405" sense="1" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>schwülwarm</orthForm>
</lexUnit>
</synset>
<synset id="s2207" category="adj" class="natPhaenomen">
<lexUnit id="l3406" sense="1" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>schwülheiß</orthForm>
</lexUnit>
</synset>
<synset id="s2208" category="adj" class="natPhaenomen">
<lexUnit id="l3407" sense="1" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>drückend</orthForm>
</lexUnit>
</synset>
<synset id="s2209" category="adj" class="natPhaenomen">
<lexUnit id="l3408" sense="1" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>lau</orthForm>
</lexUnit>
<lexUnit id="l3409" sense="1" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>mild</orthForm>
</lexUnit>
<lexUnit id="l3410" sense="1" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>lind</orthForm>
</lexUnit>
</synset>
<synset id="s2210" category="adj" class="natPhaenomen">
<lexUnit id="l3411" sense="1" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>frisch</orthForm>
</lexUnit>
</synset>
<synset id="s2211" category="adj" class="natPhaenomen">
<lexUnit id="l3412" sense="1" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>frostig</orthForm>
</lexUnit>
<lexUnit id="l132979" sense="1" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>frostkalt</orthForm>
</lexUnit>
</synset>
<synset id="s2212" category="adj" class="natPhaenomen">
<lexUnit id="l3413" sense="1" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>nasskalt</orthForm>
<oldOrthForm>naßkalt</oldOrthForm>
</lexUnit>
</synset>
<synset id="s2213" category="adj" class="natPhaenomen">
<lexUnit id="l3415" sense="1" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>nasskühl</orthForm>
<oldOrthForm>naßkühl</oldOrthForm>
</lexUnit>
</synset>
<synset id="s2214" category="adj" class="natPhaenomen">
<lexUnit id="l3417" sense="1" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>sonnig</orthForm>
</lexUnit>
</synset>
<synset id="s2215" category="adj" class="natPhaenomen">
<lexUnit id="l3418" sense="2" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>strahlend</orthForm>
</lexUnit>
</synset>
<synset id="s2216" category="adj" class="natPhaenomen">
<lexUnit id="l3419" sense="3" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>heiter</orthForm>
</lexUnit>
</synset>
<synset id="s2217" category="adj" class="natPhaenomen">
<lexUnit id="l3420" sense="1" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>sommerlich-sonnig</orthForm>
</lexUnit>
</synset>
<synset id="s2218" category="adj" class="natPhaenomen">
<lexUnit id="l3421" sense="1" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>bewölkt</orthForm>
</lexUnit>
<lexUnit id="l3422" sense="1" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>wolkig</orthForm>
</lexUnit>
</synset>
<synset id="s2219" category="adj" class="natPhaenomen">
<lexUnit id="l3423" sense="1" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>bedeckt</orthForm>
</lexUnit>
</synset>
<synset id="s2220" category="adj" class="natPhaenomen">
<lexUnit id="l3425" sense="1" source="core" namedEntity="no" artificial="no" styleMarking="no">
<orthForm>neblig</orthForm>
</lexUnit>
